[package]
name = "oblet"
version = "0.4.1"
description = "A lightweight standalone Markdown editor, Obsidian-theme compatible"
authors = ["lnabc03"]
edition = "2021"

[lib]
name = "oblet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify = "6"
window-vibrancy = "0.8"
